name: Check Blocked

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-draft:
    if: contains(github.event.pull_request.labels.*.name, 'pr:blocked')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is blocked
        run: |
          echo "This PR is currently blocked."
          exit 1